### ISSUE TITLE
Redirection error without WWW

### ISSUE THREAD

**Issue by edent** [nhsx/nhsx-website#44]
https://nhsx.nhs.uk/blogs/ redirects to https://www.nhsx.nhs.uk/ - that is, it adds the WWW but drops the path.

The path should be maintained on redirect.

**Comment by rjw1** [comment]
We haven't taken over the redirect of the apex yet. That is still on an azure system somewhere. Once we do I'll make sure this works.

**Comment by edent** [comment]
Friendly bump!

**Comment by dragon-dxw** [comment]
This has now been resolved. Thank you!
