### ISSUE TITLE
Redirect to mkdocs.org gives certificate error

### ISSUE THREAD

**Issue by octoberclub** [nhsx/nhsx-website#45]
In the documentation at [docs/source/help.md]( https://github.com/nhsx/nhsx-website/blob/c974468e88193a4d4078222037a2a2437cdd0492/docs/source/help.md#L7) there is a link to [https://mkdocs.org](https://mkdocs.org) which gives a certificate error when clicked.

The issue is reported in the repo for the site being linked [mkdocs/mkdocs#1626](https://github.com/mkdocs/mkdocs/issues/1626)

Workaround - could change the url to https://www.mkdocs.org which does not give the error

**Comment by dragondave** [comment]
I'm finding no reference in the current code to MkDocs or mkdocs, and the file in question has been deleted.
Looks like this is resolved.
Thank you for the bug report!
