### ISSUE TITLE
Duplicate base URL in base config settings

### ISSUE THREAD

**Issue by GaryJones** [nhsx/nhsx-website#50]
There are two instances of `BASE_URL` in the base config settings - with the [first](https://github.com/nhsx/nhsx-website/blob/b54592671f290c7c6912d40db827f9dae540ed13/app/config/settings/base.py#L154) seemingly belonging to a previous project.

**Comment by dragondave** [comment]
This is now fixed in the development environment. Thank you for the bug report!
