### ISSUE TITLE
Blog license about COVID-19 app appear Crown Copyright

### ISSUE THREAD

**Issue by faebug** [nhsx/nhsx-website#53]
The COVID-19 app is released on a OGL v3 license, including all documentation, to enable the benefits of public review, participation and public trust.

The related public posts about the app should be similarly released on the OGL free license, rather than the effective all rights reserved default of (c) Crown copyright displayed on the nhsx website which disallows reuse. https://www.nhsx.nhs.uk/blogs/code-behind-nhs-covid-19-app

**Comment by dragon-dxw** [comment]
I'm afraid these sorts of decisions feel out of scope for this repository, unless we're implementing a new feature to handle different licensing, and the decisions about that would be taken elsewhere.
You might have more success getting in touch directly via the [Contact us page](https://www.nhsx.nhs.uk/contact-us/) should you wish to pursue this further.
